apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::084236263360:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1HFGLJVCA3FE3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::084236263360:role/UdacityFlaskDeployCBKubectlRole
      username: build    
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-07T21:25:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1457"
  uid: 564115fb-893c-4a05-974d-e789eeb36152
